from datetime import date, timedelta
from django.core.management.base import BaseCommand
from django.db.models import Q
from django.utils import timezone

from accounts.models import AdminUser, PrivacyPolicy, Terms
from content.models import Category, Consultation, Emirate, Initiative, NewsArticle, PagePresentation, Short


class Command(BaseCommand):
    help = 'Seed production demo data for the Marage Support platform.'

    def handle(self, *args, **options):
        self.stdout.write('Seeding production data...')

        # ---------------------------------------------------------------- emirates
        emirates = [
            {
                'slug': 'abu-dhabi',
                'emirates_name': 'Abu Dhabi',
                'emirates_name_ar': 'أبوظبي',
                'title': 'Abu Dhabi - Marriage Support & Family Programs',
                'description': 'Abu Dhabi, the capital of the UAE, offers the widest range of government-backed marriage funds, family development programs, and expert pre-marital counseling across the emirate.',
                'center_count': '18 centers',
                'service_centers': 18,
                'contact_phone': '800 22 33',
                'website_url': 'https://www.visitabudhabi.ae',
                'image': 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=900&auto=format&fit=crop',
            },
            {
                'slug': 'dubai',
                'emirates_name': 'Dubai',
                'emirates_name_ar': 'دبي',
                'title': 'Dubai - Modern Family & Counseling Hub',
                'description': 'Dubai combines a modern global community with developed authorities and a wide network of private counseling centers devoted to family well-being.',
                'center_count': '22 centers',
                'service_centers': 22,
                'contact_phone': '800 44 55',
                'website_url': 'https://www.visitdubai.com',
                'image': 'https://images.unsplash.com/photo-1518684079-3c830dcef090?q=80&w=900&auto=format&fit=crop',
            },
            {
                'slug': 'sharjah',
                'emirates_name': 'Sharjah',
                'emirates_name_ar': 'الشارقة',
                'title': 'Sharjah - Heritage & Family Well-being',
                'description': 'Sharjah, the cultural capital, is home to heritage-focused family initiatives, educational programs, and social cohesion projects that strengthen marriage bonds.',
                'center_count': '14 centers',
                'service_centers': 14,
                'contact_phone': '800 66 77',
                'website_url': 'https://www.sharjah.gov.ae',
                'image': 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?q=80&w=900&auto=format&fit=crop',
            },
            {
                'slug': 'ajman',
                'emirates_name': 'Ajman',
                'emirates_name_ar': 'عجمان',
                'title': 'Ajman - Growing Community Support',
                'description': 'Ajman, a close-knit and fast-growing emirate, provides accessible marriage support programs, counseling services, and helpful community development initiatives.',
                'center_count': '8 centers',
                'service_centers': 8,
                'contact_phone': '800 88 99',
                'website_url': 'https://www.ajman.ae',
                'image': 'https://images.unsplash.com/photo-1465414829459-d228b58caf6e?q=80&w=900&auto=format&fit=crop',
            },
            {
                'slug': 'umm-al-quwain',
                'emirates_name': 'Umm Al-Quwain',
                'emirates_name_ar': 'أم القيوين',
                'title': 'Umm Al Quwain - Personalized Family Guidance',
                'description': 'Umm Al Quwain, a peaceful emirate, offers personalized family guidance, emerging marriage support programs, and carefully tailored community resources for local families.',
                'center_count': '5 centers',
                'service_centers': 5,
                'contact_phone': '800 11 22',
                'website_url': 'https://www.moec.gov.ae',
                'image': 'https://images.unsplash.com/photo-1528702748617-c64d49f918af?q=80&w=900&auto=format&fit=crop',
            },
            {
                'slug': 'ras-al-khaimah',
                'emirates_name': 'Ras Al Khaimah',
                'emirates_name_ar': 'رأس الخيمة',
                'title': 'Ras Al Khaimah - Northern Family Programs',
                'description': 'Ras Al Khaimah offers strong community development programs, dedicated family guidance services, and reliable local marriage support within a scenic northern setting.',
                'center_count': '9 centers',
                'service_centers': 9,
                'contact_phone': '800 33 44',
                'website_url': 'https://www.rak.ae',
                'image': 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=900&auto=format&fit=crop',
            },
            {
                'slug': 'fujairah',
                'emirates_name': 'Fujairah',
                'emirates_name_ar': 'الفجيرة',
                'title': 'Fujairah - Coastal Family Services',
                'description': 'Fujairah, a scenic coastal emirate, provides family support services, community resources, and personalized counseling programs that promote healthy, lasting relationships.',
                'center_count': '6 centers',
                'service_centers': 6,
                'contact_phone': '800 55 66',
                'website_url': 'https://www.fujairah.ae',
                'image': 'https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=900&auto=format&fit=crop',
            },
        ]
        for e in emirates:
            Emirate.objects.update_or_create(slug=e['slug'], defaults={**e, 'status': 'Published'})
        self.stdout.write(self.style.SUCCESS('Emirates: 7'))

        # ---------------------------------------------------------------- categories
        categories = [
            ('Marriage', 'Marriage-related content'),
            ('Family', 'Family-related content'),
            ('Education', 'Education content'),
            ('Finance', 'Financial support'),
            ('Health', 'Health and wellbeing'),
            ('Culture', 'Culture and heritage'),
            ('Service', 'Services and initiatives'),
        ]
        for name, desc in categories:
            Category.objects.update_or_create(name=name, defaults={'description': desc, 'status': 'Published'})
        self.stdout.write(self.style.SUCCESS('Categories: 7'))

        # ---------------------------------------------------------------- initiatives
        initiatives = [
            {
                'slug': 'marriage-fund-abu-dhabi',
                'title': 'Marriage Fund for Young Emiratis',
                'title_ar': 'صندوق الزواج للشباب الإماراتيين',
                'subtitle': 'Financial support of up to AED 100,000 for eligible couples',
                'subtitle_ar': 'دعم مالي يصل إلى 100,000 درهم للأزواج المؤهلين',
                'category': 'Financial Support',
                'emirates': 'abu-dhabi',
                'badge': 'Featured',
                'is_featured': True,
                'start_date': date.today() - timedelta(days=30),
                'end_date': date.today() + timedelta(days=300),
                'cover_image': 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1200&auto=format&fit=crop',
                'official_website_url': 'https://www.abudhabi.gov.ae',
                'description': 'The Marriage Fund supports young Emirati couples with a one-time financial grant to ease the costs of marriage and establish a stable family.',
                'purpose': 'To reduce the financial burden of marriage for young Emiratis and encourage stable, lasting unions.',
                'objectives': [
                    'Provide financial grants to eligible couples',
                    'Support housing and furnishing needs',
                    'Promote early marriage and family stability',
                ],
                'basic_information': [
                    'Grant amount: up to AED 100,000',
                    'Open to UAE nationals',
                    'Application via community development authorities',
                ],
                'support_offered': {
                    'financial_support': True,
                    'housing_support': True,
                    'educational_support': False,
                    'marriage_training_program': True,
                    'pre_marital_preparation': True,
                },
                'benefits': [
                    'One-time financial grant',
                    'Free pre-marital counseling sessions',
                    'Access to family support workshops',
                ],
                'contact': [
                    'Community Development Authority, Abu Dhabi',
                    'Phone: 800 22 33',
                    'Email: marriagefund@cda.gov.ae',
                ],
            },
            {
                'slug': 'dubai-family-housing',
                'title': 'Dubai Family Housing Grant',
                'title_ar': 'منحة الإسكان الأسري في دبي',
                'subtitle': 'Housing assistance for newly married couples in Dubai',
                'subtitle_ar': 'مساعدات سكنية للأزواج حديثي الزواج في دبي',
                'category': 'Housing Support',
                'emirates': 'dubai',
                'badge': 'Housing',
                'is_featured': False,
                'start_date': date.today() - timedelta(days=15),
                'end_date': date.today() + timedelta(days=250),
                'cover_image': 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
                'official_website_url': 'https://www.dm.gov.ae',
                'description': 'Dubai offers housing grants and subsidized villas for eligible newly married families to secure a comfortable home.',
                'purpose': 'Help new families secure affordable housing in Dubai.',
                'objectives': [
                    'Provide housing grants for married couples',
                    'Offer subsidized family residences',
                    'Support first-time homebuyers',
                ],
                'basic_information': [
                    'Housing grants up to AED 500,000',
                    'Subsidized villas in family communities',
                    'For UAE nationals',
                ],
                'support_offered': {
                    'financial_support': True,
                    'housing_support': True,
                    'educational_support': False,
                    'marriage_training_program': False,
                    'pre_marital_preparation': False,
                },
                'benefits': [
                    'Housing grant eligibility',
                    'Priority family housing allocations',
                    'Financial counseling support',
                ],
                'contact': [
                    'Dubai Municipality',
                    'Phone: 800 44 55',
                    'Email: housing@dm.gov.ae',
                ],
            },
            {
                'slug': 'premarital-training-program',
                'title': 'National Premarital Training Program',
                'title_ar': 'البرنامج الوطني للتدريب قبل الزواج',
                'subtitle': 'Certified workshops preparing couples for married life',
                'subtitle_ar': 'ورش عمل معتمدة تُعد الأزواج للحياة الزوجية',
                'category': 'Education',
                'emirates': 'sharjah',
                'badge': 'Training',
                'is_featured': False,
                'start_date': date.today() - timedelta(days=5),
                'end_date': date.today() + timedelta(days=365),
                'cover_image': 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=1200&auto=format&fit=crop',
                'official_website_url': 'https://www.family.gov.ae',
                'description': 'A certified training curriculum covering communication, finances, and conflict resolution for engaged couples.',
                'purpose': 'Prepare engaged couples with practical skills for a successful marriage.',
                'objectives': [
                    'Teach communication and conflict resolution skills',
                    'Provide financial literacy for couples',
                    'Issue certified completion certificates',
                ],
                'basic_information': [
                    '8-week certified program',
                    'Available in English and Arabic',
                    'Online and in-person sessions',
                ],
                'support_offered': {
                    'financial_support': False,
                    'housing_support': False,
                    'educational_support': True,
                    'marriage_training_program': True,
                    'pre_marital_preparation': True,
                },
                'benefits': [
                    'Certified marriage readiness certificate',
                    'Expert-led workshops',
                    'Personalized couple assessments',
                ],
                'contact': [
                    'Family Development Foundation',
                    'Phone: 800 66 77',
                    'Email: training@family.gov.ae',
                ],
            },
            {
                'slug': 'marriage-support-counseling',
                'title': 'UAE Marriage Support Counseling Centers',
                'title_ar': 'مراكز دعم الزواج والإرشاد في الإمارات',
                'subtitle': 'Free and subsidized counseling for couples across all emirates',
                'subtitle_ar': 'استشارات مجانية ومدعومة للأزواج في جميع الإمارات',
                'category': 'Counseling',
                'emirates': 'ras-al-khaimah',
                'badge': 'Counseling',
                'is_featured': False,
                'start_date': date.today() - timedelta(days=10),
                'end_date': date.today() + timedelta(days=365),
                'cover_image': 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=1200&auto=format&fit=crop',
                'official_website_url': 'https://www.moher.ae',
                'description': 'A nationwide network of counseling centers offering free sessions, mediation, and family guidance for couples.',
                'purpose': 'Provide accessible counseling and mediation for couples and families nationwide.',
                'objectives': [
                    'Operate counseling centers in every emirate',
                    'Offer free initial consultation sessions',
                    'Provide family mediation services',
                ],
                'basic_information': [
                    '18+ counseling centers nationwide',
                    'Free initial sessions',
                    'Confidential and certified counselors',
                ],
                'support_offered': {
                    'financial_support': False,
                    'housing_support': False,
                    'educational_support': False,
                    'marriage_training_program': False,
                    'pre_marital_preparation': True,
                },
                'benefits': [
                    'Access to certified counselors',
                    'Free introductory sessions',
                    'Family mediation and support',
                ],
                'contact': [
                    'Ministry of Community Development',
                    'Phone: 800 33 44',
                    'Email: counseling@mocd.gov.ae',
                ],
            },
        ]
        for i in initiatives:
            Initiative.objects.update_or_create(slug=i['slug'], defaults={**i, 'status': 'Published'})
        self.stdout.write(self.style.SUCCESS('Initiatives: 4'))

        # ---------------------------------------------------------------- news
        news = [
            {
                'slug': 'new-family-fund-announcement',
                'article_title': 'New Family Fund Expands Support for Young Couples',
                'article_title_ar': 'صندوق الأسرة الجديد يوسع دعمه للأزواج الشباب',
                'category': 'family',
                'source': 'government',
                'language': 'both',
                'author': 'Marage Editorial Team',
                'editorial_team': 'Family Affairs Desk',
                'organization': 'Ministry of Community Development',
                'moc': 'Ministry of Community Development',
                'city': 'Abu Dhabi',
                'emirates': 'abu-dhabi',
                'published_date': date.today() - timedelta(days=3),
                'updated_date': date.today() - timedelta(days=2),
                'content': '<p>The Ministry of Community Development has announced an expansion of the family fund, increasing support for young couples planning to marry. The program now covers additional housing and education allowances, with applications opening across all emirates.</p><p>Families can apply through the ministry\u2019s digital portal or visit any of the 18 community development centers nationwide.</p>',
                'cover_image': 'https://images.unsplash.com/photo-1495020689067-958852a7765e?q=80&w=1200&auto=format&fit=crop',
                'resources': [
                    {'title': 'Application Guide', 'url': 'https://www.mocd.gov.ae', 'type': 'application'},
                    {'title': 'Program Details', 'url': 'https://www.mocd.gov.ae/family-fund', 'type': 'document'},
                ],
            },
            {
                'slug': 'premarital-counseling-now-mandatory',
                'article_title': 'Premarital Counseling Sessions Now Offered in All Emirates',
                'article_title_ar': 'جلسات الاستشارة قبل الزواج متاحة الآن في جميع الإمارات',
                'category': 'counseling',
                'source': 'government',
                'language': 'both',
                'author': 'Marage Editorial Team',
                'editorial_team': 'Counseling Desk',
                'organization': 'Family Development Foundation',
                'moc': 'Ministry of Community Development',
                'city': 'Sharjah',
                'emirates': 'sharjah',
                'published_date': date.today() - timedelta(days=7),
                'updated_date': date.today() - timedelta(days=7),
                'content': '<p>Certified premarital counseling is now available at all 14 Sharjah family development centers. Couples can book free introductory sessions covering communication, finances, and conflict resolution.</p>',
                'cover_image': 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=1200&auto=format&fit=crop',
                'resources': [
                    {'title': 'Book a Session', 'url': 'https://www.family.gov.ae', 'type': 'booking'},
                ],
            },
            {
                'slug': 'financial-literacy-for-newlyweds',
                'article_title': 'Financial Literacy Workshops Help Newlyweds Build Strong Budgets',
                'article_title_ar': 'ورش التثقيف المالي تساعد المتزوجين حديثًا على بناء ميزانيات قوية',
                'category': 'finance',
                'source': 'government',
                'language': 'both',
                'author': 'Marage Editorial Team',
                'editorial_team': 'Finance Desk',
                'organization': 'Dubai Economy',
                'moc': 'Dubai Economy',
                'city': 'Dubai',
                'emirates': 'dubai',
                'published_date': date.today() - timedelta(days=12),
                'updated_date': date.today() - timedelta(days=12),
                'content': '<p>New financial literacy workshops are helping newlywed couples create sustainable household budgets. The sessions cover savings, investment basics, and smart debt management tailored for new families.</p>',
                'cover_image': 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1200&auto=format&fit=crop',
                'resources': [
                    {'title': 'Workshop Calendar', 'url': 'https://www.dubai.ae', 'type': 'calendar'},
                ],
            },
            {
                'slug': 'emirati-couples-sharing-stories',
                'article_title': 'Emirati Couples Share Stories of Strong, Lasting Marriages',
                'article_title_ar': 'أزواج إماراتيون يشاركون قصص زيجات ناجحة ودائمة',
                'category': 'community',
                'source': 'ngo',
                'language': 'both',
                'author': 'Marage Community Desk',
                'editorial_team': 'Community Desk',
                'organization': 'Marage Support',
                'moc': 'Marage Support',
                'city': 'Ajman',
                'emirates': 'ajman',
                'published_date': date.today() - timedelta(days=18),
                'updated_date': date.today() - timedelta(days=18),
                'content': '<p>A new series highlights real Emirati couples who credit premarital counseling, financial planning, and family support programs for their successful marriages. Their stories aim to inspire a new generation.</p>',
                'cover_image': 'https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=1200&auto=format&fit=crop',
                'resources': [
                    {'title': 'Watch Stories', 'url': 'https://www.marage.ae/stories', 'type': 'video'},
                ],
            },
            {
                'slug': 'housing-grants-umm-al-quwain',
                'article_title': 'Umm Al Quwain Launches New Housing Grants for Married Families',
                'article_title_ar': 'أم القيوين تطلق منحًا سكنية جديدة للعائلات المتزوجة',
                'category': 'policy',
                'source': 'government',
                'language': 'both',
                'author': 'Marage Editorial Team',
                'editorial_team': 'Policy Desk',
                'organization': 'Umm Al Quwain Government',
                'moc': 'Umm Al Quwain Government',
                'city': 'Umm Al Quwain',
                'emirates': 'umm-al-quwain',
                'published_date': date.today() - timedelta(days=25),
                'updated_date': date.today() - timedelta(days=25),
                'content': '<p>Umm Al Quwain has launched a new housing grant program for married families, providing land allocations and construction subsidies to eligible residents.</p>',
                'cover_image': 'https://images.unsplash.com/photo-1465414829459-d228b58caf6e?q=80&w=1200&auto=format&fit=crop',
                'resources': [
                    {'title': 'Apply Now', 'url': 'https://www.uaq.ae', 'type': 'application'},
                ],
            },
            {
                'slug': 'mental-health-support-for-families',
                'article_title': 'Mental Health Support Expands for Families Across the UAE',
                'article_title_ar': 'توسيع الدعم النفسي للعائلات في جميع أنحاء الإمارات',
                'category': 'health',
                'source': 'government',
                'language': 'both',
                'author': 'Marage Health Desk',
                'editorial_team': 'Health Desk',
                'organization': 'Emirates Health Services',
                'moc': 'Emirates Health Services',
                'city': 'Fujairah',
                'emirates': 'fujairah',
                'published_date': date.today() - timedelta(days=30),
                'updated_date': date.today() - timedelta(days=30),
                'content': '<p>Emirates Health Services has expanded family mental health programs, adding dedicated counselors and virtual consultation hours for couples and parents.</p>',
                'cover_image': 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?q=80&w=1200&auto=format&fit=crop',
                'resources': [
                    {'title': 'Find Support', 'url': 'https://www.ehs.gov.ae', 'type': 'contact'},
                ],
            },
        ]
        for n in news:
            NewsArticle.objects.update_or_create(slug=n['slug'], defaults={**n, 'status': 'Published'})
        self.stdout.write(self.style.SUCCESS('News: 6'))

        # ---------------------------------------------------------------- shorts
        shorts = [
            {
                'slug': 'effective-communication-tips',
                'video_title': '5 Communication Tips for Newlyweds',
                'video_title_ar': '5 نصائح للتواصل بين المتزوجين حديثًا',
                'category': 'Education',
                'organization': 'Marage Academy',
                'language': 'en',
                'marital_stage': 'premarital',
                'duration': '3:45',
                'published_at': timezone.now() - timedelta(days=2),
                'speaker': 'Dr. Sara Al Hashimi',
                'description': 'Practical communication techniques to strengthen your relationship from day one.',
                'video_url': 'https://www.youtube.com/watch?v=communication-tips',
                'cover_image': 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=800&auto=format&fit=crop',
                'key_topics': ['Active listening', 'Non-verbal cues', 'Conflict resolution'],
                'resources': [
                    {'title': 'Communication Guide', 'url': 'https://www.marage.ae', 'type': 'document'},
                ],
            },
            {
                'slug': 'managing-finances-together',
                'video_title': 'Managing Finances Together',
                'video_title_ar': 'إدارة الأموال معًا',
                'category': 'Finance',
                'organization': 'Marage Finance',
                'language': 'both',
                'marital_stage': 'marital',
                'duration': '4:12',
                'published_at': timezone.now() - timedelta(days=5),
                'speaker': 'Mr. Omar Al Mansoori',
                'description': 'A simple framework for building a shared household budget that works for both partners.',
                'video_url': 'https://www.youtube.com/watch?v=managing-finances',
                'cover_image': 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=800&auto=format&fit=crop',
                'key_topics': ['Budgeting', 'Savings', 'Shared goals'],
                'resources': [
                    {'title': 'Budget Template', 'url': 'https://www.marage.ae/budget', 'type': 'document'},
                ],
            },
            {
                'slug': 'premarital-preparation-checklist',
                'video_title': 'Premarital Preparation Checklist',
                'video_title_ar': 'قائمة التحضير قبل الزواج',
                'category': 'Education',
                'organization': 'Marage Academy',
                'language': 'both',
                'marital_stage': 'premarital',
                'duration': '5:00',
                'published_at': timezone.now() - timedelta(days=8),
                'speaker': 'Dr. Layla Haddad',
                'description': 'Everything engaged couples should discuss before saying yes - from finances to family expectations.',
                'video_url': 'https://www.youtube.com/watch?v=premarital-checklist',
                'cover_image': 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=800&auto=format&fit=crop',
                'key_topics': ['Financial planning', 'Family expectations', 'Career plans'],
                'resources': [
                    {'title': 'Checklist PDF', 'url': 'https://www.marage.ae/checklist', 'type': 'document'},
                ],
            },
            {
                'slug': 'cultural-traditions-heritage',
                'video_title': 'Cultural Traditions & Heritage in Emirati Weddings',
                'video_title_ar': 'التقاليد الثقافية والتراث في الأعراس الإماراتية',
                'category': 'Culture',
                'organization': 'Marage Culture',
                'language': 'ar',
                'marital_stage': 'marital',
                'duration': '6:20',
                'published_at': timezone.now() - timedelta(days=12),
                'speaker': 'Sheikha Maryam',
                'description': 'Celebrating the rich cultural heritage that shapes Emirati marriage ceremonies and family life.',
                'video_url': 'https://www.youtube.com/watch?v=emirati-traditions',
                'cover_image': 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=800&auto=format&fit=crop',
                'key_topics': ['Wedding traditions', 'Family customs', 'Heritage preservation'],
                'resources': [
                    {'title': 'Heritage Guide', 'url': 'https://www.marage.ae/heritage', 'type': 'document'},
                ],
            },
            {
                'slug': 'supporting-your-partner',
                'video_title': 'Supporting Your Partner Through Challenges',
                'video_title_ar': 'دعم شريك حياتك في التحديات',
                'category': 'Service',
                'organization': 'Marage Counseling',
                'language': 'both',
                'marital_stage': 'marital',
                'duration': '3:50',
                'published_at': timezone.now() - timedelta(days=15),
                'speaker': 'Adv. Fatima Al Zaabi',
                'description': 'How to be a supportive partner during difficult times and where to find professional help.',
                'video_url': 'https://www.youtube.com/watch?v=supporting-partner',
                'cover_image': 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=800&auto=format&fit=crop',
                'key_topics': ['Emotional support', 'Seeking help', 'Building resilience'],
                'resources': [
                    {'title': 'Support Resources', 'url': 'https://www.marage.ae/support', 'type': 'contact'},
                ],
            },
            {
                'slug': 'health-and-wellbeing-marriage',
                'video_title': 'Health & Wellbeing for a Happy Marriage',
                'video_title_ar': 'الصحة والرفاهية لزواج سعيد',
                'category': 'Health',
                'organization': 'Marage Health',
                'language': 'en',
                'marital_stage': 'marital',
                'duration': '4:30',
                'published_at': timezone.now() - timedelta(days=20),
                'speaker': 'Dr. Noura Al Marzooqi',
                'description': 'Prioritizing mental and physical wellbeing as a couple for a healthier, happier life together.',
                'video_url': 'https://www.youtube.com/watch?v=health-marriage',
                'cover_image': 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?q=80&w=800&auto=format&fit=crop',
                'key_topics': ['Mental wellbeing', 'Active lifestyle', 'Work-life balance'],
                'resources': [
                    {'title': 'Wellbeing Guide', 'url': 'https://www.marage.ae/wellbeing', 'type': 'document'},
                ],
            },
        ]
        for s in shorts:
            Short.objects.update_or_create(slug=s['slug'], defaults={**s, 'status': 'Published'})
        self.stdout.write(self.style.SUCCESS('Shorts: 6'))

        # ---------------------------------------------------------------- consultations
        consultations = [
            {
                'slug': 'effective-communication-workshop',
                'session_title': 'Effective Communication for Couples',
                'session_title_ar': 'التواصل الفعال بين الأزواج',
                'category': 'Education',
                'session_type': 'counseling',
                'emirates': 'dubai',
                'marital_stage': 'premarital',
                'language': 'both',
                'date': date.today() + timedelta(days=7),
                'start_time': '10:00',
                'end_time': '12:00',
                'duration': '2 hours',
                'is_free': True,
                'fee': 0,
                'counselor': 'Dr. Layla Haddad',
                'counselor_photo': 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&auto=format&fit=crop',
                'counselor_title': 'Licensed Family Counselor',
                'counselor_bio': 'Dr. Haddad is a licensed family counselor with 15 years of experience guiding couples toward healthier communication.',
                'max_participants': 25,
                'meeting_format': 'online',
                'session_link': 'https://meet.marage.ae/communication',
                'gallery': [
                    'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=900&auto=format&fit=crop',
                ],
                'description': 'A practical workshop on healthy communication, conflict resolution and building trust.',
                'objectives': ['Improve active listening', 'Resolve conflicts constructively', 'Build trust'],
                'what_you_will_learn': ['Active listening techniques', 'Non-violent communication', 'Conflict de-escalation'],
                'who_should_attend': ['Engaged couples', 'Newlyweds'],
                'booking_notice': 'Free session - limited seats available. Please book in advance.',
                'is_bookable': True,
            },
            {
                'slug': 'financial-planning-newlyweds',
                'session_title': 'Financial Planning for Newlyweds',
                'session_title_ar': 'التخطيط المالي للمتزوجين حديثًا',
                'category': 'Finance',
                'session_type': 'financial',
                'emirates': 'abu-dhabi',
                'marital_stage': 'marital',
                'language': 'both',
                'date': date.today() + timedelta(days=14),
                'start_time': '14:00',
                'end_time': '16:00',
                'duration': '2 hours',
                'is_free': False,
                'fee': 120.00,
                'processing_fee': 5.00,
                'discount': 0,
                'counselor': 'Mr. Omar Al Mansoori',
                'counselor_photo': 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=400&auto=format&fit=crop',
                'counselor_title': 'Certified Financial Advisor',
                'counselor_bio': 'Omar helps couples build sustainable financial plans and navigate housing and savings programs.',
                'max_participants': 40,
                'meeting_format': 'onsite',
                'gallery': [
                    'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=900&auto=format&fit=crop',
                ],
                'description': 'Budgeting, savings, housing subsidies and financial planning tailored for newlywed couples.',
                'objectives': ['Create a shared budget', 'Understand housing subsidies', 'Plan for the future'],
                'what_you_will_learn': ['Budgeting frameworks', 'Investment basics', 'Housing grant navigation'],
                'who_should_attend': ['Newlyweds', 'Couples planning finances'],
                'booking_notice': 'Paid session. Fee covers materials and refreshments.',
                'is_bookable': True,
            },
            {
                'slug': 'marriage-legal-rights',
                'session_title': 'Marriage Legal Rights in the UAE',
                'session_title_ar': 'الحقوق القانونية للزواج في الإمارات',
                'category': 'Education',
                'session_type': 'legal',
                'emirates': 'sharjah',
                'marital_stage': 'marital',
                'language': 'both',
                'date': date.today() + timedelta(days=21),
                'start_time': '11:00',
                'end_time': '13:00',
                'duration': '2 hours',
                'is_free': True,
                'fee': 0,
                'counselor': 'Adv. Fatima Al Zaabi',
                'counselor_photo': 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=400&auto=format&fit=crop',
                'counselor_title': 'Family Law Attorney',
                'counselor_bio': 'Fatima specializes in UAE family law and guides couples through their legal rights and responsibilities.',
                'max_participants': 30,
                'meeting_format': 'online',
                'session_link': 'https://meet.marage.ae/legal-rights',
                'gallery': [
                    'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=900&auto=format&fit=crop',
                ],
                'description': 'Understand your legal rights and responsibilities under UAE family law.',
                'objectives': ['Know legal rights', 'Understand marriage contracts', 'Learn dispute resolution options'],
                'what_you_will_learn': ['Marriage contract essentials', 'Legal obligations', 'Divorce and custody basics'],
                'who_should_attend': ['Engaged couples', 'Married couples'],
                'booking_notice': 'Free legal awareness session.',
                'is_bookable': True,
            },
            {
                'slug': 'premarital-health-checkup',
                'session_title': 'Premarital Health & Wellbeing Checkup',
                'session_title_ar': 'الفحص الصحي قبل الزواج والرفاهية',
                'category': 'Health',
                'session_type': 'health',
                'emirates': 'ras-al-khaimah',
                'marital_stage': 'premarital',
                'language': 'both',
                'date': date.today() + timedelta(days=28),
                'start_time': '09:00',
                'end_time': '11:00',
                'duration': '2 hours',
                'is_free': True,
                'fee': 0,
                'counselor': 'Dr. Noura Al Marzooqi',
                'counselor_photo': 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=400&auto=format&fit=crop',
                'counselor_title': 'Public Health Specialist',
                'counselor_bio': 'Dr. Noura leads premarital health programs promoting long-term wellbeing for new families.',
                'max_participants': 35,
                'meeting_format': 'onsite',
                'gallery': [
                    'https://images.unsplash.com/photo-1544027993-37dbfe43562a?q=80&w=900&auto=format&fit=crop',
                ],
                'description': 'Learn about required health screenings and how to build healthy habits as a new family.',
                'objectives': ['Understand required screenings', 'Build healthy habits', 'Plan family health'],
                'what_you_will_learn': ['Required health tests', 'Nutrition basics', 'Family wellness planning'],
                'who_should_attend': ['Engaged couples', 'Newlyweds'],
                'booking_notice': 'Free health awareness session.',
                'is_bookable': True,
            },
            {
                'slug': 'workshop-strengthening-marriage',
                'session_title': 'Workshop: Strengthening Your Marriage',
                'session_title_ar': 'ورشة عمل: تقوية زواجك',
                'category': 'Service',
                'session_type': 'workshop',
                'emirates': 'ajman',
                'marital_stage': 'marital',
                'language': 'both',
                'date': date.today() + timedelta(days=35),
                'start_time': '17:00',
                'end_time': '20:00',
                'duration': '3 hours',
                'is_free': False,
                'fee': 200.00,
                'processing_fee': 10.00,
                'discount': 20.00,
                'counselor': 'Dr. Sara Al Hashimi',
                'counselor_photo': 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&auto=format&fit=crop',
                'counselor_title': 'Relationship Coach',
                'counselor_bio': 'Dr. Sara runs immersive workshops helping couples reconnect and grow together.',
                'max_participants': 20,
                'meeting_format': 'onsite',
                'gallery': [
                    'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=900&auto=format&fit=crop',
                ],
                'description': 'An immersive half-day workshop designed to deepen connection and strengthen your marriage.',
                'objectives': ['Reconnect emotionally', 'Set shared goals', 'Create a family vision'],
                'what_you_will_learn': ['Emotional connection tools', 'Shared goal setting', 'Family vision planning'],
                'who_should_attend': ['Married couples', 'Couples seeking renewal'],
                'booking_notice': 'Includes materials and light refreshments. Early booking recommended.',
                'is_bookable': True,
            },
        ]
        for c in consultations:
            Consultation.objects.update_or_create(slug=c['slug'], defaults={**c, 'status': 'Published'})
        self.stdout.write(self.style.SUCCESS('Consultations: 5'))

        # ---------------------------------------------------------------- presentations
        presentations = [
            {
                'key': 'home',
                'title': 'Marriage Support & Family Services Across the UAE',
                'title_ar': 'دعم الزواج والخدمات الأسرية في دولة الإمارات',
                'description': 'Discover government initiatives, counseling sessions, and resources to support every stage of your marriage journey.',
                'description_ar': 'اكتشف المبادرات الحكومية وجلسات الاستشارة والموارد لدعم كل مرحلة من رحلتك الزوجية.',
                'badge': 'Your Family Support Hub',
                'hero_image': 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=1600&auto=format&fit=crop',
            },
            {
                'key': 'news',
                'title': 'Stay Informed with the Latest Marriage & Family News Across the UAE',
                'title_ar': 'ابقَ على اطلاع بآخر أخبار الزواج والأسرة في دولة الإمارات',
                'description': 'Explore curated news, updates, and announcements from trusted government agencies, family organizations, and community initiatives.',
                'description_ar': 'استكشف الأخبار والتنبيهات والتحديثات من الجهات الحكومية الموثوقة ومنظمات الأسرة ومبادرات المجتمع.',
                'badge': 'Latest Updates',
                'hero_image': 'https://images.unsplash.com/photo-1495020689067-958852a7765e?q=80&w=1200&auto=format&fit=crop',
            },
            {
                'key': 'shorts',
                'title': 'Expert Marriage & Family Advice, in Short Videos',
                'title_ar': 'نصائح الخبراء في الزواج والأسرة، في فيديوهات قصيرة',
                'description': 'Concise, practical guidance from certified experts across the UAE. Watch, learn, and grow together - one short video at a time.',
                'description_ar': 'إرشادات موجزة وعملية من خبراء معتمدين في جميع أنحاء الإمارات. شاهد وتعلم وانمو معًا - فيديو قصير في كل مرة.',
                'badge': 'Quick, Practical Guidance',
                'hero_image': 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=900&auto=format&fit=crop',
            },
            {
                'key': 'consultation',
                'title': 'Find the Right Marriage Consultation Session for a Stronger and Happier Future',
                'title_ar': 'ابحث عن جلسة الاستشارة الزوجية المناسبة لمستقبل أقوى وأكثر سعادة',
                'description': 'Explore free and paid consultation sessions offered by trusted government agencies, private organizations, and certified professionals across the UAE.',
                'description_ar': 'استكشف جلسات استشارية مجانية ومدفوعة تقدمها جهات حكومية ومنظمات خاصة ومختصون معتمدون في جميع أنحاء الإمارات.',
                'badge': 'Expert Guidance',
                'hero_image': 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=900&auto=format&fit=crop',
            },
            {
                'key': 'initiatives',
                'title': 'Explore Marriage Support Initiatives Across the UAE',
                'title_ar': 'استكشف مبادرات دعم الزواج في دولة الإمارات',
                'description': 'Financial support, housing grants, education programs and more for eligible Emirati families.',
                'description_ar': 'دعم مالي ومنح إسكان وبرامج تعليمية والمزيد للأسر الإماراتية المؤهلة.',
                'badge': 'Featured Initiative',
                'hero_image': 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=1200&auto=format&fit=crop',
            },
            {
                'key': 'emirates',
                'title': 'Discover Marriage Support Services Across the UAE Emirates',
                'title_ar': 'اكتشف خدمات دعم الزواج في إمارات دولة الإمارات',
                'description': 'Find consultation, financial help, counseling and community resources close to home in every emirate.',
                'description_ar': 'ابحث عن الاستشارة والدعم المالي والإرشاد والموارد المجتمعية بالقرب منك في كل إمارة.',
                'badge': 'Nationwide Coverage',
                'hero_image': 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1200&auto=format&fit=crop',
            },
        ]
        for p in presentations:
            PagePresentation.objects.update_or_create(key=p['key'], defaults=p)
        self.stdout.write(self.style.SUCCESS('Presentations: 6'))

        # ---------------------------------------------------------------- terms & privacy
        if not Terms.objects.exists():
            Terms.objects.create(content='<h2>Terms and Conditions</h2><p>By using the Marage Support platform you agree to these terms. Content provided is for general information and does not constitute professional advice. Consult qualified professionals for personal decisions.</p>')
        if not PrivacyPolicy.objects.exists():
            PrivacyPolicy.objects.create(content='<h2>Privacy Policy</h2><p>We value your privacy. Personal data submitted through this platform is used solely to deliver the services you request and is never sold to third parties.</p>')

        # ---------------------------------------------------------------- admin user
        if not AdminUser.objects.filter(Q(email='admin@kodevio.com') | Q(username='admin')).exists():
            AdminUser.objects.create_superuser(
                email='admin@kodevio.com',
                username='admin',
                name='Marage Admin',
                password='admin12345',
            )
            self.stdout.write(self.style.SUCCESS('Created superuser admin@kodevio.com / admin12345'))

        # ---- prune any records not part of the canonical seed (idempotency) ----
        seed_slugs = {
            Emirate: {e['slug'] for e in emirates},
            Initiative: {i['slug'] for i in initiatives},
            NewsArticle: {n['slug'] for n in news},
            Short: {s['slug'] for s in shorts},
            Consultation: {c['slug'] for c in consultations},
            PagePresentation: {p['key'] for p in presentations},
        }
        for model, slugs in seed_slugs.items():
            model.objects.exclude(pk__in=model.objects.filter(**({'slug__in': slugs} if model is not PagePresentation else {'key__in': slugs})).values('pk')).delete()

        self.stdout.write(self.style.SUCCESS('Production seed complete.'))