# Generated by Django 5.0.14 on 2026-08-08 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Reference')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('contact_number', models.CharField(max_length=30, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user_type', models.CharField(choices=[('individual', 'Individual'), ('couple', 'Couple'), ('organization', 'Organization')], default='individual', max_length=20, verbose_name='User Type')),
                ('company_or_organization', models.CharField(blank=True, max_length=200, verbose_name='Company / Organization')),
                ('seats', models.PositiveIntegerField(default=1, verbose_name='Seats')),
                ('session_date', models.DateField(blank=True, null=True, verbose_name='Session Date')),
                ('session_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Session Snapshot')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('apple_pay', 'Apple Pay')], default='card', max_length=20, verbose_name='Payment Method')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Payment Reference')),
                ('payment_success', models.BooleanField(default=False, verbose_name='Payment Success')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending_payment', 'Pending Payment')], default='pending_payment', max_length=20, verbose_name='Status')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='content.consultation')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InitiativeApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Reference')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('contact_number', models.CharField(max_length=30, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user_type', models.CharField(choices=[('individual', 'Individual'), ('couple', 'Couple'), ('organization', 'Organization')], default='individual', max_length=20, verbose_name='User Type')),
                ('user_or_organization_name', models.CharField(blank=True, max_length=200, verbose_name='User / Organization Name')),
                ('marital_status', models.CharField(blank=True, max_length=30, verbose_name='Marital Status')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('emirate', models.CharField(blank=True, max_length=30, verbose_name='Emirate')),
                ('income', models.CharField(blank=True, max_length=100, verbose_name='Income')),
                ('family_members', models.PositiveIntegerField(default=0, verbose_name='Family Members')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationality')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('received', 'Received'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='received', max_length=20, verbose_name='Status')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='content.initiative')),
            ],
            options={
                'verbose_name': 'Initiative Application',
                'verbose_name_plural': 'Initiative Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
