# Generated by Django 5.0.14 on 2026-08-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initiative_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='is_featured',
            field=models.BooleanField(
                default=False,
                help_text='If checked, this initiative is shown on the user panel (single featured).',
                verbose_name='Featured on Home Page',
            ),
        ),
    ]
