# Generated by Django 5.0.14 on 2026-08-12 07:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_initiative_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePresentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('news', 'News'), ('shorts', 'Shorts'), ('consultation', 'Consultation'), ('home', 'Home'), ('initiatives', 'Initiatives'), ('emirates', 'Emirates')], max_length=40, unique=True, verbose_name='Section Key')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=300, verbose_name='Title (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('badge', models.CharField(blank=True, max_length=120, verbose_name='Badge')),
                ('hero_image', models.CharField(blank=True, max_length=500, verbose_name='Hero Image')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Page Presentation',
                'verbose_name_plural': 'Page Presentations',
                'ordering': ['key'],
            },
        ),
    ]
