# Generated by Django 5.0.14 on 2026-09-03 10:29

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_aboutcontent_contactcontent_mediaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='hero_image',
            field=models.CharField(blank=True, help_text='Recommended 1280x600 px', max_length=500, verbose_name='Hero Image URL'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='hero_image_alt',
            field=models.CharField(blank=True, max_length=300, verbose_name='Hero Image Alt Text'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='section_visibility',
            field=models.JSONField(blank=True, default=content.models._default_section_visibility, help_text='Toggle which homepage sections render on the user panel. Keys: hero, stats, shorts, news, initiatives, consultations, emirates, cta. Missing keys default to true.', verbose_name='Section Visibility'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='is_listed',
            field=models.BooleanField(default=True, help_text='Show this initiative in the public /initiatives list. Featured initiatives are always listed.', verbose_name='Show on Initiatives Listing'),
        ),
    ]
