# Generated by Django 5.0.14 on 2026-09-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_aboutcontent_hero_image_aboutcontent_hero_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepresentation',
            name='shorts_contributors',
            field=models.JSONField(blank=True, default=list, help_text='List of contributor names shown on the Shorts page.', verbose_name='Shorts Contributors'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='shorts_faqs',
            field=models.JSONField(blank=True, default=list, help_text='List of { "question", "questionAr", "answer", "answerAr" } items shown on the Shorts page.', verbose_name='Shorts FAQs'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='shorts_topics',
            field=models.JSONField(blank=True, default=list, help_text='List of { "title", "videos", "icon" } items shown on the Shorts page.', verbose_name='Shorts Topics'),
        ),
    ]
