# Generated by Django 5.0.14 on 2026-09-05 10:31

from django.db import migrations, models


def add_columns_if_not_exists(apps, schema_editor):
    table = 'content_pagepresentation'
    columns = [
        ('initiatives_contributors', 'jsonb', "DEFAULT '[]'::jsonb"),
        ('initiatives_faqs', 'jsonb', "DEFAULT '[]'::jsonb"),
        ('initiatives_section_visibility', 'jsonb', "DEFAULT '{}'::jsonb"),
        ('initiatives_topics', 'jsonb', "DEFAULT '[]'::jsonb"),
        ('shorts_section_visibility', 'jsonb', "DEFAULT '{}'::jsonb"),
    ]
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == 'postgresql':
            for col, col_type, default in columns:
                cursor.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {col} {col_type} {default};")
        else:
            existing = [row[1] for row in cursor.execute(f"PRAGMA table_info({table});").fetchall()]
            for col, _, _ in columns:
                if col not in existing:
                    cursor.execute(f"ALTER TABLE {table} ADD COLUMN {col} json DEFAULT '[]';")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_pagepresentation_shorts_contributors_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='pagepresentation',
                    name='initiatives_contributors',
                    field=models.JSONField(blank=True, default=list, help_text='List of contributor names shown on the Initiatives page.', verbose_name='Initiatives Contributors'),
                ),
                migrations.AddField(
                    model_name='pagepresentation',
                    name='initiatives_faqs',
                    field=models.JSONField(blank=True, default=list, help_text='List of { "question", "questionAr", "answer", "answerAr" } items shown on the Initiatives page.', verbose_name='Initiatives FAQs'),
                ),
                migrations.AddField(
                    model_name='pagepresentation',
                    name='initiatives_section_visibility',
                    field=models.JSONField(blank=True, default=dict, help_text='Controls which sections render on the Initiatives user-panel page. Keys: hero, topics, contributors, faqs, cta. Missing keys default to true.', verbose_name='Initiatives Section Visibility'),
                ),
                migrations.AddField(
                    model_name='pagepresentation',
                    name='initiatives_topics',
                    field=models.JSONField(blank=True, default=list, help_text='List of { "title", "videos" } items shown on the Initiatives page.', verbose_name='Initiatives Topics'),
                ),
                migrations.AddField(
                    model_name='pagepresentation',
                    name='shorts_section_visibility',
                    field=models.JSONField(blank=True, default=dict, help_text='Controls which sections render on the Shorts user-panel page. Keys: hero, topics, contributors, faqs. Missing keys default to true.', verbose_name='Shorts Section Visibility'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_columns_if_not_exists, noop_reverse),
            ],
        ),
    ]
