# Generated by Django 5.0.14 on 2026-09-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_pagepresentation_initiatives_contributors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepresentation',
            name='consultation_contributors',
            field=models.JSONField(blank=True, default=list, help_text='List of contributor names shown on the Consultation page.', verbose_name='Consultation Contributors'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='consultation_faqs',
            field=models.JSONField(blank=True, default=list, help_text='List of { "question", "questionAr", "answer", "answerAr" } items shown on the Consultation page.', verbose_name='Consultation FAQs'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='consultation_section_visibility',
            field=models.JSONField(blank=True, default=dict, help_text='Controls which sections render on the Consultation user-panel page. Keys: hero, topics, contributors, faqs, cta. Missing keys default to true.', verbose_name='Consultation Section Visibility'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='consultation_topics',
            field=models.JSONField(blank=True, default=list, help_text='List of { "title", "titleAr", "videos" } items shown on the Consultation page.', verbose_name='Consultation Topics'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='emirates_contributors',
            field=models.JSONField(blank=True, default=list, help_text='List of contributor names shown on the Emirates page.', verbose_name='Emirates Contributors'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='emirates_faqs',
            field=models.JSONField(blank=True, default=list, help_text='List of { "question", "questionAr", "answer", "answerAr" } items shown on the Emirates page.', verbose_name='Emirates FAQs'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='emirates_section_visibility',
            field=models.JSONField(blank=True, default=dict, help_text='Controls which sections render on the Emirates user-panel page. Keys: hero, topics, contributors, faqs, cta. Missing keys default to true.', verbose_name='Emirates Section Visibility'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='emirates_topics',
            field=models.JSONField(blank=True, default=list, help_text='List of { "title", "titleAr", "videos" } items shown on the Emirates page.', verbose_name='Emirates Topics'),
        ),
    ]
