# Generated by Django 5.0.14 on 2026-09-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_pagepresentation_consultation_contributors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepresentation',
            name='news_contributors',
            field=models.JSONField(blank=True, default=list, help_text='List of contributor names shown on the News page.', verbose_name='News Contributors'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='news_faqs',
            field=models.JSONField(blank=True, default=list, help_text='List of { "question", "questionAr", "answer", "answerAr" } items shown on the News page.', verbose_name='News FAQs'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='news_section_visibility',
            field=models.JSONField(blank=True, default=dict, help_text='Controls which sections render on the News user-panel page. Keys: hero, topics, contributors, faqs, cta, categories, orgs. Missing keys default to true.', verbose_name='News Section Visibility'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='news_topics',
            field=models.JSONField(blank=True, default=list, help_text='List of { "title", "videos" } items shown on the News page.', verbose_name='News Topics'),
        ),
    ]
