# Generated by Django 5.0.14 on 2026-09-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_shorts_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='section_visibility',
            field=models.JSONField(blank=True, default=dict, help_text='Keys: hero, ourStory, ourMission, ourVision, ourObjective, whatWeOffer, ourImpact, whyChoose, coreValues', verbose_name='Section Visibility'),
        ),
        migrations.AddField(
            model_name='contactcontent',
            name='section_visibility',
            field=models.JSONField(blank=True, default=dict, help_text='Keys: hero, formLabels, contactInfo, locationMap', verbose_name='Section Visibility'),
        ),
    ]
