# Generated by Django 5.0.14 on 2026-09-14

import content.models
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_add_section_visibility_to_about_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_text', models.CharField(blank=True, max_length=800, verbose_name='Brand Text')),
                ('brand_text_ar', models.CharField(blank=True, max_length=800, verbose_name='Brand Text (Arabic)')),
                ('government_label', models.CharField(blank=True, max_length=300, verbose_name='Government Label')),
                ('government_label_ar', models.CharField(blank=True, max_length=300, verbose_name='Government Label (Arabic)')),
                ('quick_links', models.JSONField(blank=True, default=list, help_text='Array of objects: {label, labelAr, href}', verbose_name='Quick Links')),
                ('resource_links', models.JSONField(blank=True, default=list, help_text='Array of objects: {label, labelAr, href}', verbose_name='Resource Links')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Address')),
                ('address_ar', models.CharField(blank=True, max_length=500, verbose_name='Address (Arabic)')),
                ('copyright_text', models.CharField(blank=True, help_text='Shown after © {year}. e.g. "All rights reserved."', max_length=300, verbose_name='Copyright Text')),
                ('copyright_text_ar', models.CharField(blank=True, max_length=300, verbose_name='Copyright Text (Arabic)')),
                ('built_for_text', models.CharField(blank=True, help_text='Text next to the heart icon. e.g. "Built for Emirati Families"', max_length=300, verbose_name='Built For Text')),
                ('built_for_text_ar', models.CharField(blank=True, max_length=300, verbose_name='Built For Text (Arabic)')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('section_visibility', models.JSONField(blank=True, default=content.models._default_footer_section_visibility, help_text='Controls which footer columns render on the user panel. Keys: brand, quickLinks, resources, contacts, bottomBar. Missing keys default to true.', verbose_name='Section Visibility')),
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Content',
            },
        ),
    ]
