# Generated by Django 5.0.14 on 2026-09-14

import content.models
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_footercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontent',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Footer logo image URL. Falls back to the bundled logo when empty.', max_length=500, verbose_name='Logo URL'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='quick_links_heading',
            field=models.CharField(blank=True, max_length=200, verbose_name='Quick Links Heading'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='quick_links_heading_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Quick Links Heading (Arabic)'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='resource_links_heading',
            field=models.CharField(blank=True, max_length=200, verbose_name='Resources Heading'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='resource_links_heading_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Resources Heading (Arabic)'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='contacts_heading',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contacts Heading'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='contacts_heading_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contacts Heading (Arabic)'),
        ),
    ]
