# Generated by Django 5.0.14 on 2026-09-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_add_ar_fields_auto_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='ar_is_machine',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Internal registry of Arabic fields generated by the translation service. Fields not listed here are human-reviewed and are never overwritten automatically.', verbose_name='Machine-generated Arabic Fields'),
        ),
        migrations.AddField(
            model_name='category',
            name='ar_is_machine',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Internal registry of Arabic fields generated by the translation service. Fields not listed here are human-reviewed and are never overwritten automatically.', verbose_name='Machine-generated Arabic Fields'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ar_is_machine',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Internal registry of Arabic fields generated by the translation service. Fields not listed here are human-reviewed and are never overwritten automatically.', verbose_name='Machine-generated Arabic Fields'),
        ),
        migrations.AddField(
            model_name='contactcontent',
            name='ar_is_machine',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Internal registry of Arabic fields generated by the translation service. Fields not listed here are human-reviewed and are never overwritten automatically.', verbose_name='Machine-generated Arabic Fields'),
        ),
        migrations.AddField(
            model_name='emirate',
            name='ar_is_machine',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Internal registry of Arabic fields generated by the translation service. Fields not listed here are human-reviewed and are never overwritten automatically.', verbose_name='Machine-generated Arabic Fields'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='ar_is_machine',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Internal registry of Arabic fields generated by the translation service. Fields not listed here are human-reviewed and are never overwritten automatically.', verbose_name='Machine-generated Arabic Fields'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='ar_is_machine',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Internal registry of Arabic fields generated by the translation service. Fields not listed here are human-reviewed and are never overwritten automatically.', verbose_name='Machine-generated Arabic Fields'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='ar_is_machine',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Internal registry of Arabic fields generated by the translation service. Fields not listed here are human-reviewed and are never overwritten automatically.', verbose_name='Machine-generated Arabic Fields'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='ar_is_machine',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Internal registry of Arabic fields generated by the translation service. Fields not listed here are human-reviewed and are never overwritten automatically.', verbose_name='Machine-generated Arabic Fields'),
        ),
        migrations.AddField(
            model_name='pagepresentation',
            name='ar_is_machine',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Internal registry of Arabic fields generated by the translation service. Fields not listed here are human-reviewed and are never overwritten automatically.', verbose_name='Machine-generated Arabic Fields'),
        ),
        migrations.AddField(
            model_name='short',
            name='ar_is_machine',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Internal registry of Arabic fields generated by the translation service. Fields not listed here are human-reviewed and are never overwritten automatically.', verbose_name='Machine-generated Arabic Fields'),
        ),
    ]
