# Generated by Django 5.0.14 on 2026-09-15 11:50

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_aboutcontent_ar_is_machine_category_ar_is_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='section_visibility',
            field=models.JSONField(blank=True, default=content.models._default_about_section_visibility, help_text='Keys: ourStory, ourMission, ourVision, ourObjective, whatWeOffer, ourImpact, whyChoose, coreValues. Missing keys default to true.', verbose_name='Section Visibility'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='section_visibility',
            field=models.JSONField(blank=True, default=content.models._default_contact_section_visibility, help_text='Keys: formLabels, contactInfo, locationMap. Missing keys default to true.', verbose_name='Section Visibility'),
        ),
        migrations.AlterField(
            model_name='pagepresentation',
            name='consultation_section_visibility',
            field=models.JSONField(blank=True, default=content.models._default_consultation_section_visibility, help_text='Controls which sections render on the Consultation user-panel page. Keys: topics, contributors, faqs, cta. Missing keys default to true.', verbose_name='Consultation Section Visibility'),
        ),
        migrations.AlterField(
            model_name='pagepresentation',
            name='emirates_section_visibility',
            field=models.JSONField(blank=True, default=content.models._default_emirates_section_visibility, help_text='Controls which sections render on the Emirates user-panel page. Keys: topics, contributors, faqs, cta. Missing keys default to true.', verbose_name='Emirates Section Visibility'),
        ),
        migrations.AlterField(
            model_name='pagepresentation',
            name='initiatives_section_visibility',
            field=models.JSONField(blank=True, default=content.models._default_initiatives_section_visibility, help_text='Controls which sections render on the Initiatives user-panel page. Keys: topics, contributors, faqs, cta. Missing keys default to true.', verbose_name='Initiatives Section Visibility'),
        ),
        migrations.AlterField(
            model_name='pagepresentation',
            name='news_section_visibility',
            field=models.JSONField(blank=True, default=content.models._default_news_section_visibility, help_text='Controls which sections render on the News user-panel page. Keys: topics, contributors, faqs, cta, categories, orgs. Missing keys default to true.', verbose_name='News Section Visibility'),
        ),
        migrations.AlterField(
            model_name='pagepresentation',
            name='shorts_section_visibility',
            field=models.JSONField(blank=True, default=content.models._default_shorts_section_visibility, help_text='Controls which sections render on the Shorts user-panel page. Keys: topics, contributors, faqs, cta. Missing keys default to true.', verbose_name='Shorts Section Visibility'),
        ),
    ]
