# Generated by Antigravity on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_canonical_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='File Size (bytes)'),
        ),
    ]
