# Generated by Django 5.0.14 on 2026-09-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_alter_mediaitem_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='basic_information_ar',
            field=models.JSONField(blank=True, default=list, verbose_name='Basic Information (Arabic)'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='contact_ar',
            field=models.JSONField(blank=True, default=list, verbose_name='Contact (Arabic)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Pending', 'Pending')], default='Published', help_text='Controls public visibility. Only Published categories appear on public /categories; Draft and Pending are excluded. Admin APIs still return all statuses.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='is_bookable',
            field=models.BooleanField(default=True, help_text='Server-side gate for POST /api/consultations/book. When false, booking is rejected even if Show Booking is enabled.', verbose_name='Is Bookable'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='show_booking',
            field=models.BooleanField(default=True, help_text='When disabled, public API marks is_bookable as false and the detail page hides the Booking CTA; use is_bookable to block actual bookings server-side.', verbose_name='Show Booking'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='show_doctor',
            field=models.BooleanField(default=True, help_text='When disabled, public API omits counselor, counselorAr, counselor_photo, counselor_title, counselor_titleAr, counselor_bio and counselor_bioAr and the detail page hides the Doctor/Counselor block.', verbose_name='Show Doctor'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='show_gallery',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty gallery and the detail page hides the Gallery block.', verbose_name='Show Gallery'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='show_learn_more',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty learn_more and the detail page hides the Learn More block.', verbose_name='Show Learn More'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='show_schedule',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty schedule and the detail page hides the Schedule block.', verbose_name='Show Schedule'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Pending', 'Pending')], default='Draft', help_text='Controls public visibility. Only Published sessions appear on public endpoints; Draft and Pending return 404 and are excluded from lists, search and direct slug/title access. Admin APIs still return all statuses.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='emirate',
            name='show_status',
            field=models.BooleanField(default=True, help_text='When disabled, public API omits the status badge/label and the detail page hides the Status row; the record remains accessible if status is Published.', verbose_name='Show Status'),
        ),
        migrations.AlterField(
            model_name='emirate',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Pending', 'Pending')], default='Published', help_text='Controls public visibility. Only Published emirates appear on public endpoints; Draft and Pending return 404 and are excluded from lists, search and direct slug access. Admin APIs still return all statuses.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='If checked, this initiative is shown on the user panel (single featured). Only visible when status is Published.', verbose_name='Featured on Home Page'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='is_listed',
            field=models.BooleanField(default=True, help_text='Show this initiative in the public /initiatives list. Featured initiatives are always listed. Only Published and listed items appear publicly.', verbose_name='Show on Initiatives Listing'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='show_about',
            field=models.BooleanField(default=True, help_text='When disabled, public API omits description, descriptionAr, purpose, purposeAr, objectives and objectivesAr and the detail page hides the About block.', verbose_name='Show About'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='show_application_form',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty contact and the detail page hides the Application Form block.', verbose_name='Show Application Form'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='show_benefits',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty benefits/benefitsAr and the detail page hides the Benefits block.', verbose_name='Show Benefits'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='show_support_offered',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty supportOffered and the detail page hides the Support Offered block.', verbose_name='Show Support Offered'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Pending', 'Pending')], default='Draft', help_text='Controls public visibility. Only Published items appear on public endpoints; Draft and Pending return 404 and are excluded from lists, featured, search, emirate-nested lists and direct slug access. Admin APIs still return all statuses.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='show_article_info',
            field=models.BooleanField(default=True, help_text='When disabled, public API omits author, authorAr, editorial_team, organization, moc, city and emirates and the detail page hides the Article Info block.', verbose_name='Show Article Info'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='show_related_resources',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty resources and the detail page hides the Related Resources block.', verbose_name='Show Related Resources'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='show_related_stories',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty relatedStories and the detail page hides the Related Stories block.', verbose_name='Show Related Stories'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='show_share',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty share_url and the detail page hides the Share block.', verbose_name='Show Share'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Pending', 'Pending')], default='Draft', help_text='Controls public visibility. Only Published items appear on public endpoints; Draft and Pending return 404 and are excluded from lists, search, and related stories. Admin APIs still return all statuses.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='short',
            name='show_key_topics',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty key_topics and the detail page hides the Key Topics block.', verbose_name='Show Key Topics'),
        ),
        migrations.AlterField(
            model_name='short',
            name='show_related',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty relatedVideos and the detail page hides the Related Videos block.', verbose_name='Show Related'),
        ),
        migrations.AlterField(
            model_name='short',
            name='show_resources',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty resources and the detail page hides the Resources block.', verbose_name='Show Resources'),
        ),
        migrations.AlterField(
            model_name='short',
            name='show_share',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty share_url and the detail page hides the Share block.', verbose_name='Show Share'),
        ),
        migrations.AlterField(
            model_name='short',
            name='show_speaker',
            field=models.BooleanField(default=True, help_text='When disabled, public API returns empty speaker / speakerAr and the detail page hides the Speaker row.', verbose_name='Show Speaker'),
        ),
        migrations.AlterField(
            model_name='short',
            name='show_views',
            field=models.BooleanField(default=True, help_text='When disabled, public API omits views count (returns 0) and the detail page hides the Views row.', verbose_name='Show Views'),
        ),
        migrations.AlterField(
            model_name='short',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Pending', 'Pending')], default='Draft', help_text='Controls public visibility. Only Published items appear on public endpoints; Draft and Pending return 404 and are excluded from lists, search, related content, and emirate-nested initiatives. Admin APIs still return all statuses.', max_length=20, verbose_name='Status'),
        ),
    ]
