# Generated by Django 5.0.14 on 2026-09-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_initiative_basic_information_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='city_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='City (Arabic)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='organization_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organization (Arabic)'),
        ),
    ]
