# Generated by Django 5.0.14 on 2026-09-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_newsarticle_city_ar_newsarticle_organization_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='website_button_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website Button Label'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='website_button_label_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website Button Label (Arabic)'),
        ),
    ]
