# Generated by Django 5.0.14 on 2026-09-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_initiative_website_button_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='emirate',
            name='browse_initiatives_url',
            field=models.CharField(blank=True, help_text='Destination of the Browse Initiatives button on the public emirate detail page. Empty defaults to /initiatives.', max_length=1000, verbose_name='Browse Initiatives URL'),
        ),
    ]
