# Generated by Django 5.0.14 on 2026-09-03 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('total_chunks', models.PositiveIntegerField()),
                ('received_chunks', models.JSONField(blank=True, default=list, help_text='List of chunk indexes that have been uploaded (e.g. [0,1,2]).')),
                ('total_size', models.PositiveBigIntegerField(default=0, help_text='Sum of all chunk byte sizes; checked against MAX_UPLOAD_SIZE_BYTES on completion.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='pending', max_length=20)),
                ('media_item_id', models.UUIDField(blank=True, help_text='Set after completion: the MediaItem pk that owns the assembled file.', null=True)),
                ('uploaded_by', models.CharField(blank=True, help_text='AdminUser identifier (email) for auditing.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Upload Session',
                'verbose_name_plural': 'Upload Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
